---
version: "3"
services:
 devopsdb:
   container_name: devopsapp
   image: bhass9624/main:appimage
   ports:
     - "3306:3306"

 application:
   image: bhass9624/main:appimage
   container_name: containerapp
   ports:
     - "1234:8080"
   depends_on:
     - "devopsdb"
